# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nico\AUPay\src\windows\ui\AddUserShortDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(278, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_school_id = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_school_id.setFont(font)
        self.line_school_id.setMaxLength(30)
        self.line_school_id.setObjectName("line_school_id")
        self.verticalLayout.addWidget(self.line_school_id)
        self.combo_user_type = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.combo_user_type.setFont(font)
        self.combo_user_type.setObjectName("combo_user_type")
        self.combo_user_type.addItem("")
        self.combo_user_type.addItem("")
        self.combo_user_type.addItem("")
        self.verticalLayout.addWidget(self.combo_user_type)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_add_user = QtWidgets.QPushButton(Dialog)
        self.button_add_user.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_add_user.setFont(font)
        self.button_add_user.setStyleSheet("")
        self.button_add_user.setObjectName("button_add_user")
        self.verticalLayout.addWidget(self.button_add_user)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add User"))
        self.line_school_id.setPlaceholderText(_translate("Dialog", "School ID"))
        self.combo_user_type.setItemText(0, _translate("Dialog", "User"))
        self.combo_user_type.setItemText(1, _translate("Dialog", "Teller"))
        self.combo_user_type.setItemText(2, _translate("Dialog", "Business"))
        self.button_add_user.setText(_translate("Dialog", "Add User"))
