# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nico\AUPay\src\windows\ui\ChangeOTPDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 313)
        Dialog.setAutoFillBackground(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qrcodeimg = QtWidgets.QLabel(Dialog)
        self.qrcodeimg.setText("")
        self.qrcodeimg.setObjectName("qrcodeimg")
        self.verticalLayout.addWidget(self.qrcodeimg)
        self.line_otp = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_otp.setFont(font)
        self.line_otp.setObjectName("line_otp")
        self.verticalLayout.addWidget(self.line_otp)
        self.line_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_password.setFont(font)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.button_confirm_otp = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.button_confirm_otp.setFont(font)
        self.button_confirm_otp.setObjectName("button_confirm_otp")
        self.verticalLayout.addWidget(self.button_confirm_otp)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change OTP"))
        self.line_otp.setPlaceholderText(_translate("Dialog", "Enter 6-Digit OTP"))
        self.line_password.setPlaceholderText(_translate("Dialog", "Password"))
        self.button_confirm_otp.setText(_translate("Dialog", "Confirm OTP"))
