# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nico\AUPay\src\windows\ui\ChargebackTransactionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(268, 212)
        Dialog.setMinimumSize(QtCore.QSize(268, 212))
        Dialog.setMaximumSize(QtCore.QSize(268, 212))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.amountLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.amountLabel.setFont(font)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        self.amountLineEdit = QtWidgets.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.amountLineEdit.setFont(font)
        self.amountLineEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.amountLineEdit.setMaximum(100000.0)
        self.amountLineEdit.setObjectName("amountLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.amountLineEdit)
        self.buttonScanBusiness = QtWidgets.QPushButton(Dialog)
        self.buttonScanBusiness.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.buttonScanBusiness.setFont(font)
        self.buttonScanBusiness.setCheckable(False)
        self.buttonScanBusiness.setChecked(False)
        self.buttonScanBusiness.setObjectName("buttonScanBusiness")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.buttonScanBusiness)
        self.buttonScanUser = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.buttonScanUser.setFont(font)
        self.buttonScanUser.setObjectName("buttonScanUser")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonScanUser)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonSave_addTransaction = QtWidgets.QPushButton(Dialog)
        self.buttonSave_addTransaction.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.buttonSave_addTransaction.setFont(font)
        self.buttonSave_addTransaction.setObjectName("buttonSave_addTransaction")
        self.verticalLayout.addWidget(self.buttonSave_addTransaction)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chargeback"))
        self.amountLabel.setText(_translate("Dialog", "Amount:"))
        self.buttonScanBusiness.setText(_translate("Dialog", "Verify Business"))
        self.buttonScanUser.setText(_translate("Dialog", "Verify User"))
        self.buttonSave_addTransaction.setText(_translate("Dialog", "Chargeback"))
