# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nico\AUPay\src\windows\ui\ChangeOTPDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 358)
        Dialog.setAutoFillBackground(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.qrcodeimg = QtWidgets.QLabel(Dialog)
        self.qrcodeimg.setText("")
        self.qrcodeimg.setObjectName("qrcodeimg")
        self.verticalLayout.addWidget(self.qrcodeimg)
        self.line_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_password.setFont(font)
        self.line_password.setMaxLength(100)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        self.line_otp = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_otp.setFont(font)
        self.line_otp.setMaxLength(6)
        self.line_otp.setObjectName("line_otp")
        self.verticalLayout.addWidget(self.line_otp)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.button_confirm_otp = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.button_confirm_otp.setFont(font)
        self.button_confirm_otp.setObjectName("button_confirm_otp")
        self.verticalLayout.addWidget(self.button_confirm_otp)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change OTP"))
        self.label.setText(_translate("Dialog", "Scan this QR Code in the authenticator app on your mobile phone."))
        self.label_2.setText(_translate("Dialog", " (Authy, Google Authenticator, Microsoft Authenticator, etc.)"))
        self.line_password.setPlaceholderText(_translate("Dialog", "Password"))
        self.line_otp.setPlaceholderText(_translate("Dialog", "6-Digit OTP"))
        self.button_confirm_otp.setText(_translate("Dialog", "Confirm OTP"))
