# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nico\AUPay\src\windows\ui\ChangePasswordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(237, 204)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_old_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_old_password.setFont(font)
        self.line_old_password.setMaxLength(50)
        self.line_old_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.line_old_password.setObjectName("line_old_password")
        self.verticalLayout.addWidget(self.line_old_password)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line_new_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_new_password.setFont(font)
        self.line_new_password.setMaxLength(50)
        self.line_new_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.line_new_password.setObjectName("line_new_password")
        self.verticalLayout.addWidget(self.line_new_password)
        self.line_confirm_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.line_confirm_password.setFont(font)
        self.line_confirm_password.setMaxLength(50)
        self.line_confirm_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.line_confirm_password.setObjectName("line_confirm_password")
        self.verticalLayout.addWidget(self.line_confirm_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button_change_password = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.button_change_password.setFont(font)
        self.button_change_password.setObjectName("button_change_password")
        self.verticalLayout.addWidget(self.button_change_password)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change Password"))
        self.line_old_password.setPlaceholderText(_translate("Dialog", "Old Password"))
        self.line_new_password.setPlaceholderText(_translate("Dialog", "New Password"))
        self.line_confirm_password.setPlaceholderText(_translate("Dialog", "Confirm Password"))
        self.button_change_password.setText(_translate("Dialog", "Change Password"))
