# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 290)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 341, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonDelete_deleteUser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonDelete_deleteUser.setObjectName("buttonDelete_deleteUser")
        self.horizontalLayout.addWidget(self.buttonDelete_deleteUser)
        self.buttonCancel_deleteUser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonCancel_deleteUser.setObjectName("buttonCancel_deleteUser")
        self.horizontalLayout.addWidget(self.buttonCancel_deleteUser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self._id_deleteUser = QtWidgets.QLineEdit(Dialog)
        self._id_deleteUser.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self._id_deleteUser.setObjectName("_id_deleteUser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Delete User"))
        self.label.setText(_translate("Dialog", "Are you sure you want to delete this user?"))
        self.buttonDelete_deleteUser.setText(_translate("Dialog", "Delete"))
        self.buttonCancel_deleteUser.setText(_translate("Dialog", "Cancel"))
