def Logout(self):
    self.stackedWidget.setCurrentIndex(0)
    self.lineSchoolId_login.setText("")
    self.linePassword_login.setText("")
    resetOtherWindow(self)
    print("Logout Successfully")

def resetOtherWindow(self):
    self.userTable_Window.clearSelection()
    self.tableInventory_business.clearSelection()
    self.tableCart_business.clearSelection()
    self.tableTransactions_business.clearSelection()
    self.tabletTransactions_teller.clearSelection()
    self.tableUsers_administrator.clearSelection()
    self.transactionsTable_administrator.clearSelection()
    self.lineSearchTransactions_business.setText("")
    self.lineSearchInventory_business.setText("")
    self.lineSchoolId_business.setText("")
    self.lineAmount_business.setText("")
    self.textDescription_business.setText("")
    self.lineSchoolId_teller.setText("")
    self.lineAmount_teller.setText("")
    self.textDescription_teller.setText("")
    self.lineSearchUser_administrator.setText("")
    self.lineSearchTransaction_administrator.setText("")

