# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginMainWindow(object):
    def setupUi(self, LoginMainWindow):
        LoginMainWindow.setObjectName("LoginMainWindow")
        LoginMainWindow.resize(205, 187)
        LoginMainWindow.setMinimumSize(QtCore.QSize(205, 176))
        LoginMainWindow.setMaximumSize(QtCore.QSize(205, 187))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\qt\\../src/resources/aupay-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.idLine = QtWidgets.QLineEdit(self.centralwidget)
        self.idLine.setMaxLength(15)
        self.idLine.setObjectName("idLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.idLine)
        self.passwordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLine.setInputMask("")
        self.passwordLine.setMaxLength(20)
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setClearButtonEnabled(False)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.passwordLine)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setMouseTracking(True)
        self.loginButton.setObjectName("loginButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.loginButton)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        LoginMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 205, 21))
        self.menubar.setObjectName("menubar")
        LoginMainWindow.setMenuBar(self.menubar)

        self.retranslateUi(LoginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginMainWindow)

    def retranslateUi(self, LoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginMainWindow.setWindowTitle(_translate("LoginMainWindow", "AUPay Login"))
        self.idLine.setPlaceholderText(_translate("LoginMainWindow", "School ID"))
        self.passwordLine.setPlaceholderText(_translate("LoginMainWindow", "Password"))
        self.loginButton.setText(_translate("LoginMainWindow", "Login"))
