# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(217, 173)
        Dialog.setMaximumSize(QtCore.QSize(325, 302))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/aupay-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.idLine = QtWidgets.QLineEdit(self.widget)
        self.idLine.setObjectName("idLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.idLine)
        self.passwordLine = QtWidgets.QLineEdit(self.widget)
        self.passwordLine.setInputMask("")
        self.passwordLine.setMaxLength(20)
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setClearButtonEnabled(False)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.passwordLine)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.loginButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setMouseTracking(True)
        self.loginButton.setObjectName("loginButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.loginButton)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AUPay Login"))
        self.idLine.setPlaceholderText(_translate("Dialog", "School ID"))
        self.passwordLine.setPlaceholderText(_translate("Dialog", "Password"))
        self.loginButton.setText(_translate("Dialog", "Login"))
# import aupay-resources_rc
